### ISSUE TITLE
Missing grounded actions.

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#570] opened 2024-02-21 11:07 UTC
**Describe the bug**
For some reason, some grounded actions are unavailable when using `Pyperplan` Grounder.

**To Reproduce**
```
from unified_planning.io import PDDLReader
from unified_planning.shortcuts import *

domain  = './domain.pddl'
problem = './problem.pddl'
task = PDDLReader().parse_problem(domain, problem)

with Compiler(problem_kind=task.kind, compilation_kind=CompilationKind.GROUNDING) as grounder:
    print(f'Grounder name: {grounder.name}')
    grounded_problem = grounder.compile(task, compilation_kind=CompilationKind.GROUNDING).problem

grounded_actions = [str(a.name) for a in grounded_problem.actions]

is_action_missing = not 'drive_truck1_distributor0_distributor0'in grounded_actions

with open('grounded_actions.txt', 'w') as f:
    for item in grounded_actions:
        f.write("%s\n" % item)
```

**Screenshots**
<img width="895" alt="Screenshot 2024-02-21 at 11 05 30 AM" src="https://github.com/aiplan4eu/unified-planning/assets/9129265/2b3f7804-4915-4f15-89f4-7e0b229e9c2d">

**Additional context**
[instance.zip](https://github.com/aiplan4eu/unified-planning/files/14358542/instance.zip)

**Comment by alvalentini** [comment] 2024-02-21 13:01
Hi @MFaisalZaki! The reason is that the grounder removes all the grounded actions that are inapplicable or not useful to solve the problem. The smarter the grounder, the fewer grounded actions are generated.

**Comment by MFaisalZaki** [comment] 2024-02-21 13:04
That is so true @alvalentini, but I think this could impact when trying to solve goal recognition as planning tasks since an observation is a grounded action which may not be generated by the grounder. Is there any flag I can set to force the grounder to generate all actions?

**Comment by alvalentini** [comment] 2024-02-21 13:30
It is possible using this [grounder](https://github.com/aiplan4eu/unified-planning/blob/master/unified_planning/engines/compilers/grounder.py#L223) with the option `prune_actions=False`.

```python
with Compiler(name='up_grounder', params={'prune_actions':False}) as grounder:
    grounded_problem = grounder.compile(task).problem
```

or 

```python
from unified_planning.engines.compilers.grounder import Grounder
grounder = Grounder(prune_actions=False)
grounded_problem = grounder.compile(task).problem
```

**Comment by MFaisalZaki** [comment] 2024-02-21 13:49
Awesome, thanks @alvalentini.

**Comment by alvalentini** [comment] 2024-02-21 15:39
If the issue is solved, can you close the issue? Thanks!

**Closed** 2024-03-02 12:28 UTC
