### ISSUE TITLE
pip install installing old version of UPF

### ISSUE THREAD

**Issue by MannavaVivek** [aiplan4eu/unified-planning#544] opened 2023-12-08 13:22 UTC
I am installing UPF via pip 

`pip install unified-planning[engines]`

but it installs 0.4.0 which doesnt work for my code. 

> Collecting unified-planning[engines]
  Using cached unified_planning-1.0.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: pyparsing in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from unified-planning[engines]) (3.1.1)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from unified-planning[engines]) (3.2.1)
Collecting tarski[arithmetic] (from unified-planning[engines])
  Using cached tarski-0.8.2-py3-none-any.whl (213 kB)
Collecting up-pyperplan==1.0.0 (from unified-planning[engines])
  Using cached up_pyperplan-1.0.0-py3-none-any.whl.metadata (285 bytes)
Collecting up-tamer==1.0.0 (from unified-planning[engines])
  Using cached up_tamer-1.0.0-py3-none-any.whl.metadata (266 bytes)
Collecting up-enhsp==0.0.15 (from unified-planning[engines])
  Using cached up_enhsp-0.0.15-py3-none-any.whl.metadata (190 bytes)
INFO: pip is looking at multiple versions of unified-planning[engines] to determine which version is compatible with other requirements. This could take a while.
Collecting unified-planning[engines]
  Using cached unified_planning-0.6.0-py3-none-any.whl (582 kB)
Collecting up-pyperplan==0.3.0.4.dev1 (from unified-planning[engines])
  Using cached up_pyperplan-0.3.0.4.dev1-py3-none-any.whl (12 kB)
Collecting up-tamer==0.3.1.22.dev1 (from unified-planning[engines])
  Using cached up_tamer-0.3.1.22.dev1-py3-none-any.whl (13 kB)
Collecting up-enhsp==0.0.13 (from unified-planning[engines])
  Using cached up_enhsp-0.0.13-py3-none-any.whl (25.8 MB)
Collecting unified-planning[engines]
  Using cached unified_planning-0.5.0-py3-none-any.whl (339 kB)
Collecting up-pyperplan==0.3.0 (from unified-planning[engines])
  Using cached up_pyperplan-0.3.0-py3-none-any.whl (12 kB)
Collecting up-tamer==0.3.0 (from unified-planning[engines])
  Using cached up_tamer-0.3.0-py3-none-any.whl (13 kB)
Collecting up-enhsp==0.0.9 (from unified-planning[engines])
  Using cached up_enhsp-0.0.9-py3-none-any.whl (25.8 MB)
Collecting unified-planning[engines]
  Using cached unified_planning-0.4.2-py3-none-any.whl (230 kB)
Collecting up-pyperplan==0.2.0 (from unified-planning[engines])
  Using cached up_pyperplan-0.2.0-py3-none-any.whl (11 kB)
Collecting up-tamer==0.2.0 (from unified-planning[engines])
  Using cached up_tamer-0.2.0-py3-none-any.whl (12 kB)
Collecting up-enhsp==0.0.5 (from unified-planning[engines])
  Using cached up_enhsp-0.0.5-py3-none-any.whl (25.8 MB)
Collecting unified-planning[engines]
  Using cached unified_planning-0.4.1-py3-none-any.whl (230 kB)
Collecting up-enhsp==0.0.4 (from unified-planning[engines])
  Using cached up_enhsp-0.0.4-py3-none-any.whl (25.9 MB)
Collecting unified-planning[engines]
  Using cached unified_planning-0.4.0-py3-none-any.whl (230 kB)
WARNING: unified-planning 0.4.0 does not provide the extra 'engines'
Installing collected packages: unified-planning
Successfully installed unified-planning-0.4.0

I tried to force the package version to 1.0.0 but it throws the following error

> Collecting unified-planning==1.0.0 (from unified-planning[engines]==1.0.0)
  Using cached unified_planning-1.0.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: pyparsing in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from unified-planning==1.0.0->unified-planning[engines]==1.0.0) (3.1.1)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from unified-planning==1.0.0->unified-planning[engines]==1.0.0) (3.2.1)
Collecting tarski[arithmetic] (from unified-planning[engines]==1.0.0)
  Using cached tarski-0.8.2-py3-none-any.whl (213 kB)
Collecting up-pyperplan==1.0.0 (from unified-planning[engines]==1.0.0)
  Using cached up_pyperplan-1.0.0-py3-none-any.whl.metadata (285 bytes)
Collecting up-tamer==1.0.0 (from unified-planning[engines]==1.0.0)
  Using cached up_tamer-1.0.0-py3-none-any.whl.metadata (266 bytes)
Collecting up-enhsp==0.0.15 (from unified-planning[engines]==1.0.0)
  Using cached up_enhsp-0.0.15-py3-none-any.whl.metadata (190 bytes)
INFO: pip is looking at multiple versions of unified-planning[engines] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement up-fast-downward==0.2.3; extra == "engines" (from unified-planning[engines]) (from versions: 0.4.1)
ERROR: No matching distribution found for up-fast-downward==0.2.3; extra == "engines"

I tried just the package without engines and I can install that, but when i add engines or just fast-downward, it is throwing this issue. 

I am using python version 3.10 and have upgraded pip to the latest available

I followed the same commands on my ubuntu laptop with the same python installation and it worked there.

**Comment by jendrikseipp** [comment] 2024-01-25 08:35
I think it would be good to release a new version soon. Version 1.0.0 has lots of problems that seem to already be fixed in the latest prerelease versions. For example, the command line entry point `up` immediately crashes in version 1.0.0.

**Comment by alvalentini** [comment] 2024-02-09 13:30
We released a new version!
Your problem should be fixed now, so I close the issue. Feel free to reopen it if the problem is not completely solved.

**Closed by alvalentini** 2024-02-09 13:30 UTC
