### ISSUE TITLE
broken initialisation of ENHSPAnytimeEngine on python3.8

### ISSUE THREAD

**Issue by nicholasRossetti** [aiplan4eu/unified-planning#575] opened 2024-03-04 09:12 UTC
Hi, I installed unified planning using the command pip install unified-planning[engines] in docker https://hub.docker.com/r/huggingface/transformers-pytorch-gpu using python 3.8 but using the imports:
import unified_planning
from unified_planning.shortcuts import *
I obtain the following error doing every command in UP:
File /usr/local/lib/python3.8/dist-packages/up_enhsp/enhsp_planner.py:95, in ENHSPAnytimeEngine()
     [94](https://vscode-remote+ssh-002dremote-002b10-002e20-002e30-002e114.vscode-resource.vscode-cdn.net/usr/local/lib/python3.8/dist-packages/up_enhsp/enhsp_planner.py:94) class ENHSPAnytimeEngine(ENHSPEngine, PDDLAnytimePlanner):
---> [95](https://vscode-remote+ssh-002dremote-002b10-002e20-002e30-002e114.vscode-resource.vscode-cdn.net/usr/local/lib/python3.8/dist-packages/up_enhsp/enhsp_planner.py:95)     def __init__(self, params: str | None = None):
     [96](https://vscode-remote+ssh-002dremote-002b10-002e20-002e30-002e114.vscode-resource.vscode-cdn.net/usr/local/lib/python3.8/dist-packages/up_enhsp/enhsp_planner.py:96)         ENHSPEngine.__init__(self,params)
     [97](https://vscode-remote+ssh-002dremote-002b10-002e20-002e30-002e114.vscode-resource.vscode-cdn.net/usr/local/lib/python3.8/dist-packages/up_enhsp/enhsp_planner.py:97)         PDDLAnytimePlanner.__init__(self)

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by alvalentini** [comment] 2024-03-04 14:19
The error is due to a syntax introduced in python 3.10.

Try to upgrade `up-enhsp` to version `0.0.25`.

**Comment by MathisFederico** [comment] 2024-03-12 21:01
I had the same problem, but it was fixed when bumping to `up-enhsp>=0.0.25`

**Comment by alvalentini** [comment] 2024-04-15 08:17
This issue seems to be fixed now, so I close the issue. Feel free to reopen it if the problem is not completely solved.

**Closed by alvalentini** 2024-04-15 08:17 UTC
